### ISSUE TITLE
Join forces with an existing wiki engine?

### ISSUE THREAD

**Issue by dandv** [txcsmad/node-wiki#1]
Good to see a wiki developed in Node, but sad to see it didn't get much traction.

Would it make sense to join forces with one of the more popular and active projects? The top three are [Jingo](https://github.com/claudioc/jingo), [openKB](https://github.com/mrvautin/openKB) and [Hazel](https://github.com/wkallhof/Hazel).

Thanks!

**Comment by nishanths** [comment]
@dandv thanks for the links :)
this was primarily intended to show how to make a wiki app from basics for a web development workshop.
